name: Deploy main
on:
  workflow_dispatch:
jobs:
  slack_notification_start:
    name: Slack Notification1
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        run: echo "STARTED."
#         uses: rtCamp/action-slack-notify@v2
#         env:
#           SLACK_COLOR: ${{ job.status }}
#           SLACK_ICON: https://github.com/rtCamp.png?size=48
#           SLACK_MESSAGE: "Starting cron serverless deploy :rocket:"
#           SLACK_TITLE: Deploy dev
#           SLACK_USERNAME: github
#           SLACK_WEBHOOK: https://hooks.slack.com/services/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
  deploy:
    name: Serverless Deploy
    needs:
      - slack_notification_start
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@main
        with:
          ref: main
      - uses: actions/setup-node@main
        with:
          node-version: "16.14.2"
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Configuring AWS credentials using role based access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::378176467373:role/github-action-iam-role
          role-duration-seconds: 1200
          aws-region: us-east-1
      - name: Install dependencies
        run: npm install --force
      - name: Creating .env file
        run: sh ./scripts/getEnvVars.sh us-east-1 development
      - name: Deploy
        run: sls deploy -s dev --region us-east-1
  slack_notification_end:
    name: Slack Notification
    needs:
      - slack_notification_start
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        run: echo "COMPLETED."
#         uses: rtCamp/action-slack-notify@v2
#         env:
#           SLACK_COLOR: ${{ job.status }}
#           SLACK_ICON: https://github.com/rtCamp.png?size=48
#           SLACK_MESSAGE: "Successfully deployed cron serverless :white_check_mark:"
#           SLACK_TITLE: Deploy dev
#           SLACK_USERNAME: github
#           SLACK_WEBHOOK: https://hooks.slack.com/services/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
