name: Hello World
on:
  workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Slack Notification - Start
        if: always()
        uses: rtCamp/action-slack-notify@v2
        with:
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          SLACK_MESSAGE: "Workflow Started :rocket:"
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON: https://example.com/github-actions-icon.png
          SLACK_COLOR: good

      - name: Run Hello World
        run: exit 1

      - name: Slack Notification - Failed
        runs-on: ubuntu-latest

        needs: build

        steps:
          - name: Slack Notification
        if: steps.check_job_status.outputs.status == 'failure'
        uses: rtCamp/action-slack-notify@v2
        with:
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          SLACK_MESSAGE: "Workflow Failed :x:"
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON: https://example.com/github-actions-icon.png
          SLACK_COLOR: danger
