name: Slack Notification on Job Failure

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: First Job
        run: exit 1  # Simulating a failure

  job2:
    runs-on: ubuntu-latest

    needs: job1

    steps:
      - name: Second Job
        run: echo "Error First job failed!"

  send-notification:
    runs-on: ubuntu-latest

    needs: job2

    if: ${{ always() }}

    steps:
      - name: Send Slack notification
        run: echo "always runs!"

