name: Hello World

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Intentionally Fail
        run: exit 1

      - name: Slack Notification - Success
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          echo "Success notification"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Success notification"}' $SLACK_WEBHOOK

      - name: Slack Notification - Failure
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          echo "Failure notification"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Failure notification"}' $SLACK_WEBHOOK

      - name: Print Hello World
        run: echo "FAILED."
