name: Hello World

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Slack Notification - Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: good
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "Hello World job succeeded :white_check_mark:"
          SLACK_TITLE: Hello World - Success
          SLACK_USERNAME: github
          SLACK_WEBHOOK: https://hooks.slack.com/services/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

      - name: Slack Notification - Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "Hello World job failed :x:"
          SLACK_TITLE: Hello World - Failure
          SLACK_USERNAME: github
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
