name: Hello World

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Slack Notification - Success
        if: success()
      - name: Print Hello World
        run: echo "Hello, World!"
      - name: Slack Notification - Failure
        if: failure()
      - name: Print Hello World
        run: echo "FAILED"
