name: Slack Notification on Job Failure

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your job steps here

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your job steps here

  send-notification:
    needs: [job1, job2]  # Specify the jobs that need to complete before sending the notification

    runs-on: ubuntu-latest
    if: ${{ needs.job1.result == 'failure' || needs.job2.result == 'failure' }}

    steps:
      - name: Send Slack notification on failure
        uses: rtCamp/action-slack-notify@v2.0.0
        with:
          status: ${{ job.status }}
          fields: repo,message,actor,commit,job,took,workflow,workflow_run
        env:
          SLACK_CHANNEL: your-slack-channel
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
