name: Hello World

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Intentionally Fail
        run: exit 1

      - name: Slack Notification - Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        with:
          entryPoint: send
          args: --webhook-url ${{ secrets.SLACK_WEBHOOK }} --message "Success notification"

      - name: Slack Notification - Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        with:
          entryPoint: send
          args: --webhook-url ${{ secrets.SLACK_WEBHOOK }} --message "Failure notification"

      - name: Print Hello World
        run: echo "FAILED."
